[project]
name = "cag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "python-magic>=0.4.27",
]

[build-system]
requires = ['setuptools']
build-backend = 'setuptools.build_meta'
